CREATE VOLATILE MULTISET TABLE USER_LOGIN._2092_PAIRWISE_DISTANCES 
     (
       ID1 VARCHAR(64) CHARACTER SET Latin NOT CaseSpecific,
       ID2 VARCHAR(64) CHARACTER SET Latin NOT CaseSpecific,
       EDIT_DISTANCES
       )
NO PRIMARY INDEX ON COMMIT PRESERVE ROWS;