INSERT INTO USER_LOGIN._2092_PAIRWISE_DISTANCES
WITH FEATURE_DISTANCES AS
(
SELECT 

SET_1.ID_SET_1 AS ID1,
SET_2.ID_SET_2 AS ID2,
QUERY_FEATURE_DISTANCE

FROM SET_1
INNER JOIN SET_2
ON 1=1
AND SET_1.ID_SET_1 < SET_2.ID_SET_2
AND CONDITION_JOINTURE
AND SET_1.date_commande > SET_2.date_commande
),
SET_2 AS 
(
QUERY_SET_2
),
SET_1 AS
(
QUERY_SET_1
),
TOP_20 AS 
(
SELECT TOP 20 KEY, Count(*) AS cmpt
FROM USER_LOGIN._2092_CLUSTER_DATA T1
WHERE KEY IS NOT NULL GROUP BY 1 ORDER BY 2 DESC
)
SELECT *
FROM FEATURE_DISTANCES
